### PR TITLE
Auth tests

### PR DESCRIPTION
**Pull request by Temiloluwa-Ogundiran**
### 1. /api/v1/auth/register
- should return status code 201 and send user data back on success
- should return an error for wrong user input
- should return an error for duplicate email or username

### 2. /api/v1/auth/login
- should return status code 201 and send user data back on success
- should return an error if user not found
- should return an error if password is wrong

### For endpoints
* /api/v1/auth/password-reset
* /api/v1/auth/password-reset/:userId/:token

### CODE REVIEW

**Comment by Temiloluwa-Ogundiran** [comment]
For endpoints
- /api/v1/auth/password-reset
- /api/v1/auth/password-reset/:userId/:token

E2E would be the best but I can still go on to write unit tests if you want

**Comment by Nathan-Somto** [comment]
Awesome, a few things to correct before we merge
- can you please edit your commit message to match conventional commits 
i.e ```test(auth): add unit tests for auth controllers.```
- lastly pr's should be done on the staging branch (not main).

**Comment by Nathan-Somto** [comment]
> For endpoints
> 
> * /api/v1/auth/password-reset
> * /api/v1/auth/password-reset/:userId/:token
> 
> E2E would be the best but I can still go on to write unit tests if you want

Alright, E2E is fine

**Comment by Temiloluwa-Ogundiran** [comment]
so can you merge this now before I continue

**Pull request closed without merging**
