### PR TITLE
feat: update schema

### PR DESCRIPTION
**Pull request by Temiloluwa-Ogundiran**
## 1. Added
```
onDelete: Cascade
```
to relationship to avoid deletion anomaly

## 2. Updated Topic table 
- to have one to many relationship with flashcards 
- added shareCode field to hold the code that will be added to base url to share flashcard sets
- added createdAt field

### CODE REVIEW

**Review by Nathan-Somto — CHANGES_REQUESTED** [review]
Hi , temi nice work but you forgot to add the file url link to topics.

**Comment by Temiloluwa-Ogundiran** [comment]
oh sorry about about , will do now

**Comment by Temiloluwa-Ogundiran** [comment]
Added fileUrl

**Comment by Nathan-Somto** [comment]
Yeah everything looks good, the cascade was a nice touch.

**Pull request merged**
