### PR TITLE
feat: Implement main topic endpoints (#11)

### PR DESCRIPTION
**Pull request by Temiloluwa-Ogundiran**
## In this Commit  I implemented the following endpoints
- GET /topics?page=:page
- GET /topics/:topicId/flashcards
- POST /topics/manual-create
- DELETE /topics/:topicId
- PATCH  /topics/:topicId

Already tested all endpoints implemented with postman

### Todo

- [ ] Write Unit Test Cases for endpoints after logic has been confirmed

### CODE REVIEW

**Review by Nathan-Somto — CHANGES_REQUESTED** [review]
looks good,  few changes
1.  why are you using any for the auth middleware? ( 🤔 )
2.  please could you refactor all your schema validations into the validator folder please.

**Comment by Nathan-Somto** [comment]
I just realized something,
i have been working on the flashcard endpoints and I  realized that there is currently no way to check if the authorized user is the owner of the flashcards they wish to update or delete 😞

**Comment by Temiloluwa-Ogundiran** [comment]
i used any with the auth middleware because it throws an error, I think it is because of the unresolved promised in the auth middleware (dont really know)

**Comment by Temiloluwa-Ogundiran** [comment]
> I just realized something, i have been working on the flashcard endpoints and I realized that there is currently no way to check if the authorized user is the owner of the flashcards they wish to update or delete 😞

Since the flashcard collection are typically under a topic you check for the topic which the flashcards are on and check if user is the owner
```
    const topic = await prisma.topic.findUnique({
      where: { topicId, userId: user.userId }
    })
```

**Comment by Temiloluwa-Ogundiran** [comment]
> i used any with the auth middleware because it throws an error, I think it is because of the unresolved promised in the auth middleware (dont really know)

this
```
router.use(auth)
```
give the following error
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(req: Request, _res: Response, next: NextFunction) => Promise<void>' is not assignable to parameter of type 'PathParams'.ts(2769)
index.d.ts(153, 5): The last overload is declared here.
(alias) const auth: (req: Request, _res: Response, next: NextFunction) => Promise<void>
import auth
```

**Comment by Nathan-Somto** [comment]
I fixed the issue in my branch, I  forgot to import the type ``Request and Response`` in the auth middleware file

**Comment by Temiloluwa-Ogundiran** [comment]
> I fixed the issue in my branch, I forgot to import the type `Request and Response` in the auth middleware file

when you merge your branch to staging, it would be refactored

**Comment by Temiloluwa-Ogundiran** [comment]
Wait I made a mistake

**Pull request merged**
